### ISSUE TITLE
Not really an issue but on Ubuntu I got told to uninstall some kernel modules when i started the REPL

### ISSUE THREAD

**Issue by bubblebabyboi** [tenderlove/asmrepl#3]
Not sure if that is intended or not? 

![image](https://user-images.githubusercontent.com/29047827/143991144-a7104a37-4e99-4be8-94c3-cc252b4b28f6.png)

does anyone know if its safe to uninstall these?

**Comment by easyaspi314** [comment]
Just a coincidence.
