### ISSUE TITLE
Not work on MacOS?

### ISSUE THREAD

**Issue by adamgogogo** [tenderlove/asmrepl#8]
run asmrepl error after sudo gem install asmrepl: 
`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': /Library/Ruby/Gems/2.6.0/gems/asmrepl-1.1.0/lib/asmrepl/assembler.rb:7: syntax error, unexpected in, expecting when (SyntaxError)
      in [:command, [:instruction, in...
      ^~`

**Comment by tenderlove** [comment]
Looks like you're using an old version of Ruby.  I'll try to make it work with Ruby 2.6, but I don't use it regularly.  For now, can you try upgrading Ruby to at least 2.7?

Thanks.

**Comment by adamgogogo** [comment]
Thanks reply, I will try newer ruby~
